name: graphql_fragment_generator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  build_config: ^0.4.2
  source_gen: ^0.9.5
  code_builder: ^3.3.0
  analyzer: ^0.39.10
  graphql_fragment_annotation: ^0.0.1
  json_annotation: 3.0.1
