name: graphql_fragment_annotation
description: A annotation for graphql_fragment_generator.
version: 0.0.1
author:
homepage: https://github.com/kwmt/GraphQLFragmentGenerator/tree/master/graphql_fragment_annotation

environment:
  sdk: ">=2.7.0 <3.0.0"
